### ISSUE TITLE
Getting the tab information from electron window

### ISSUE THREAD

**Issue by Worie** [sentialx/electron-extensions#9]
Hi! First things first, huge thank you for developing the package and actually discussing with Electron dev team in regards of supporting chrome extensions (non devtools ones) natively. 

I have an extension that needs to access `tab.audible` - though without `chrome.tabs.query` working properly I don't know how to access the only "tab" that is open in electron window.

`background.js`
```
chrome.runtime.onConnect.addListener(async function (port) {
  port.onMessage.addListener(async function handler(msg, sender) {
      // is it possible to access the tab info that sent the message here?
  });
});
```

I am not even sure if I do get the tab instance, will `audible` property be working... 

If you could guide me in that matter - that would be great, and if it's not possible, I am willing to try and implement this piece of API, though I would need some guidance as well.

Thanks again for the great package and working on electron+chrome extensions combo!

**Comment by sentialx** [comment]
Hi, there is a `tab` object in the `sender` parameter. So you may want to use `sender.tab.audible`.

**Comment by Worie** [comment]
Thanks for fast reply! Unfortunately, `audible` property is missing in `sender.tab`.

```
{ 
   "active":false,
   "autoDiscardable":false,
   "discarded":false,
   "highlighted":false,
   "id":2,
   "incognito":false,
   "index":2,
   "pinned":false,
   "selected":false,
   "title":"localhost:9080",
   "url":"http://localhost:9080/",
   "windowId":2
}
```

I assume it's not implemented by `electron` nor `electron-extensions` then?  Not sure if it's easy/possible to polyfill it somehow.

**Comment by Worie** [comment]
nice! any plans for the release? :)

**Comment by sentialx** [comment]
https://github.com/sentialx/electron-extensions/releases/tag/v3.0.0

**Comment by Worie** [comment]
You're always one step ahead :) 

I'm just wondering - does this data that get's injected into `tab` object is generated once, say per page load - or is it recomputing those properties (for example audible) per each reference?

I'm asking, because the extension that I am working on (and it has been working on Chromium itself) does something like this:

- Every N miliseconds, asks background script for audio playing in the tabs 
- Background scripts replies with the tabs that are currently playing
- Content script gets this value injected into global scope via script tag, so it can be accessed on the client side.

Below the code, adjusted for Electron purposes.

`manifest.json`
```
{
  "manifest_version": 2,
  "name": "AudioDetector",
  "version": "0.1",
  "background": {
    "scripts": [
      // polyfill for promises
      "chrome-extension-async.js",
      "background.js"
    ]
  },
  "content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "js": ["content.js"],
      "all_frames": true
    }
  ],
  "permissions": [
    "tabs",
    "http://*/",
    "https://*/"
  ]
}
```

`content.js`
```
const startDetection = () => {

  return new Promise(async (res, reject) => {
    var port = chrome.runtime.connect({ name: "requestAudioState" });

    setInterval(() => {
        port.postMessage({});
    }, 250);

    port.onMessage.addListener(function requestAudio(msg) {
      
      var elt = document.createElement("script");
      elt.innerHTML = `
        window.audioState = Boolean(${msg.playing});
      `;
      document.head.appendChild(elt);
      elt.remove();
    });
  });
};

startDetection();
```

`background.js`
```
chrome.runtime.onConnect.addListener(async function (port) {
  port.onMessage.addListener(async function handler(msg, obj) {
    port.postMessage({
      playing: obj.sender.tab.playing,
    });
  });
});
```

Visiting for example `https://youtube.com/` should have `window.audioState` false when no audio is played, and `window.audioState` true when it does (that's the behavior working in Chromium). 

Unfortunately, when I run this in electron using your package, it's always `false` - thus I'm wondering whether the value gets recomputed on each call. If I send whole tab object to the content script (stringified) - it's exactly same object. Have you perhaps tested it to check whether `audible` was `true` in some scenarios? Can't get that to work. Ty!

**Comment by sentialx** [comment]
@Worie That's weird, because the `audible` property is being recomputed on each call. I will need to investigate it.

**Comment by sentialx** [comment]
@Worie Okay, I published 4.0.0 to npm. Also, please be aware of breaking changes: https://github.com/sentialx/electron-extensions/releases/tag/v4.0.0

**Comment by Worie** [comment]
Hey hey! TY for amazing support :) 

Unfortunately, I'm still having issues after migrating to `4.0.*`. 

When new `import { ExtensibleSession } from 'electron-extensions/main';` is added to the project and I try to load extension with 👇 
```
app.on('ready', () => {
  const extensions = new ExtensibleSession(session.defaultSession);
  extensions.loadExtension('/Users/wojtek/projects/manual-qaer/extensions/chrome/audio-detector');
```

My electron app crashes and devtools get disconeccted (though my extension is not a devtools one) with such message:
![image](https://user-images.githubusercontent.com/6313514/65855550-7cff1180-e35f-11e9-9d28-17e7b0ff471d.png)

Electron shows up with blank page. When I try to reload it, app seems loading - then devtools crash and the application goes blank. 

This does not happen if I downgrade to `3.0.0` with `import { ExtensibleSession } from 'electron-extensions';` - even though the `audible` property is not recomputed, surely.

**Comment by sentialx** [comment]
Could you reproduce it using `electron-quick-start`?

**Comment by Worie** [comment]
Yes. Same thing happens. You can see this commit: https://github.com/Worie/electron-quick-start/commit/66b8a88100cd56760891c6a287a5b8c97317d163 and run it on master from this fork: https://github.com/Worie/electron-quick-start .

**Comment by sentialx** [comment]
@Worie Okay, I published 4.0.2 with the fix.

**Comment by Worie** [comment]
Nice! Now it's working like expected, ty! :)
